# Generated by Django 4.1.7 on 2023-04-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog1", "0003_template_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="media")),
                ("fb_link", models.CharField(default=None, max_length=100)),
                ("insta_link", models.CharField(default=None, max_length=100)),
                ("twitter_link", models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
