# Generated by Django 4.1.7 on 2023-04-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog1", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="image_4",
            field=models.ImageField(default=0, upload_to="media"),
            preserve_default=False,
        ),
    ]
